name: "NameService"
supportedstandards: ["NEP-11"]
safemethods: ["balanceOf", "decimals", "symbol", "totalSupply", "tokensOf", "ownerOf",
              "tokens", "properties", "roots", "getPrice", "isAvailable", "getRecords",
              "getAllRecords",
              "resolve", "version"]
events:
  - name: RegisterDomain
    parameters:
      - name: name
        type: String
  - name: AddRecord
    parameters:
      - name: name
        type: String
      - name: type
        type: Integer
  - name: DeleteRecord
    parameters:
      - name: name
        type: String
      - name: type
        type: Integer
  - name: DeleteRecords
    parameters:
      - name: name
        type: String
      - name: type
        type: Integer
  - name: DeleteDomain
    parameters:
      - name: name
        type: String
  - name: Transfer
    parameters:
      - name: from
        type: Hash160
      - name: to
        type: Hash160
      - name: amount
        type: Integer
      - name: tokenId
        type: ByteArray
permissions:
  - hash: fffdc93764dbaddd97c48f252a53ea4643faa3fd
    methods: ["update"]
  - methods: ["onNEP11Payment"]
