wallet: "../../frostfs-aio/wallets/wallet1.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
nns_contract: "8477fcff838587103b4d008a198a4a0c3a62a5b2"
storage_node: "localhost:8080"
storage_container: "At5n3Y8fFiKuXjJGALswFhQ4Y2bNe1J4RmWQYkcMRu8m"
listen_address: ":5555"
ticket_api_url: "https://678b8b8a1a6b89b27a2aaf17.mockapi.io/jsonticket/tickets/ticket/"